### PR TITLE
add EmoteSearch plugin

### PR DESCRIPTION
**Pull request by Ckath**
this is the only thing somewhat maintained in my scuffed discord repo and you're pretty much the only one who maintains it at this point, so just have it in this repo. I'm probably going to nuke the old repo some day anyway.

### CODE REVIEW

**Comment by rauenzi** [comment]
You're really gunna nuke it? :(

**Comment by Ckath** [comment]
I dont think anything is up to date besides emotesearch these days, its also filled with questionable stuff and both my shittiest and most starred repo.

it has to go at some point

**Comment by rauenzi** [comment]
I haven't tested anything else in the repo tbh, but I can give it a quick glance

**Comment by rauenzi** [comment]
FixSize and StartOnline should still work. SendRaw and TabComplete might

**Comment by Ckath** [comment]
oh yeah tab complete was from eshankia and those others were all a minimal amount of lines

**Pull request merged**
