### PR TITLE
[AccountDetailsPlus] Fix popout wrap nested prop selector

### LINKED ISSUE #577: [Bug] Enabling AccountDetailsPlus hides the account panel on bottom left
**Which plugin/theme is this about?**
AccountDetailsPlus

**Describe the Bug**
When the plugin is enabled, the popout works, but it hides the account panel.
When I disable the plugin, the account panel shows up again.

**To Reproduce**
Simply install the plugin and enable it, then completely restart Discord.

**Expected Behavior**
The account panel should be hidden.

**Screenshots**
[https://cdn.discordapp.com/attachments/847748368787963906/961102006498508860/unknown.png?size=4096](url)

**Discord Version**
Canary 122654 (a920ed1)
BetterDiscord 1.5.2
Host 1.0.45 Windows 11 64-Bit (10.0.22000.593)

**Additional Context**
Try to recreate the bug in the EXACT same Windows environment, with the same Canary version.

### PR DESCRIPTION
**Pull request by BrandonXLF**
Fixes #577

### CODE REVIEW

**Review by bill-zhanxg — APPROVED** [review]
Works

**Review by xBiei — APPROVED** [review]

**Comment by awooooool** [comment]
Shouldn't you change the one inside `src/plugins` folder instead?

**Comment by BrandonXLF** [comment]
> Shouldn't you change the one inside `src/plugins` folder instead?

Yes you're right, I didn't notice that folder initially, I'll update it later today.

**Comment by BrandonXLF** [comment]
Fixed by #610

**Pull request closed without merging**
