### PR TITLE
[BlurNSFW] Hover on main part of channels.

### PR DESCRIPTION
**Pull request by SmolAlli**
Discord made a change that makes an `a` element be hover-able when not clicked onto the image. At least, that's what I fixed to get it to work lol.

### CODE REVIEW

**Comment by SmolAlli** [comment]
Fixes #570

**Comment by yorik100** [comment]
Disabling Blur When Focussed doesn't work anymore now

**Comment by Zzeyy** [comment]
Yes, the images stay blurred even when hovering over them.

Guessing by how long does this bug exist, allow me to ask, is this whole project abandoned?

**Review by Zzeyy — COMMENTED** [review]
Not helping. I think it has a small influence on how videos appear, but that's all.

**Comment by davidbmaier** [comment]
Was just trying to fix the same thing and had a very similar solution before I found this PR lol
This looks like the cleanest solution and works fine for me, any chance we could get this merged? @rauenzi

**Comment by NooblePrime** [comment]
Worked flawless for me. I agree with @davidbmaier, it definitely needs to be merged. It feels like this project has been abandoned by its original creator, but it shouldn't take much effort for him to just merge this with it, right?

**Comment by SmolAlli** [comment]
he's busy a lot and he'll get to it when he can, it was originally denied because i didnt change the source code. this has since been changed

**Comment by Zzeyy** [comment]
> he's busy a lot and he'll get to it when he can, it was originally denied because i didnt change the source code. this has since been changed

Source? Can you prove that he actually is doing something? I can prove nothing but that all the plugins got quietly abandoned.

**Comment by Zzeyy** [comment]
Also hovering over gifs is still broken.

**Comment by rauenzi** [comment]
> Source? Can you prove that he actually is doing something? I can prove nothing but that all the plugins got quietly abandoned.

This sort of thing is most definitely unnecessary.

**Pull request merged**
