### PR TITLE
Fixed missing PermissionViewer button for text channels

### PR DESCRIPTION
**Pull request by Leopixelo**

### CODE REVIEW

**Comment by Leopixelo** [comment]
The context button on text channels was missing because the array wasn't correctly deconstructed.

**Comment by QbDesu** [comment]
this is the same as #420 (although you at least also patched the source file)

**Comment by Leopixelo** [comment]
Yes. And mine works, for me at least.

**Comment by DS-GitHub** [comment]
After applying this, (Canary) The plugin normally worked including solved text channel plugin problem.

**Pull request closed without merging**
