### PR TITLE
Add copy userid for rightclick event on member list

### PR DESCRIPTION
**Pull request by bycop**
Able to right click on any user from the member list of any roles to copy the id directly.

### CODE REVIEW

**Comment by rauenzi** [comment]
Please modify the actual source files and use correct indentation levels

**Comment by bycop** [comment]
> Please modify the actual source files and use correct indentation levels

Normally it's ok

**Comment by rauenzi** [comment]
You still did not modify the plugin source file... 

https://github.com/rauenzi/BetterDiscordAddons/blob/master/src/plugins/RoleMembers/index.js

**Comment by bycop** [comment]
Oh I didn't know the difference mb, i'll make it

**Comment by bycop** [comment]
Edited

**Comment by bycop** [comment]
Hi, any news about this ?

**Pull request closed without merging**
