### PR TITLE
BlurNSFW added Coming soon features

### PR DESCRIPTION
**Pull request by ImAFrogOwO**
from the coming soon features I added the Group and the user (dm) Blur Media feature

### CODE REVIEW

**Comment by rauenzi** [comment]
Does not edit source files. Makes unnecessary changes to markdown files.

**Comment by ImAFrogOwO** [comment]
So do you want me to restore the original markdown and wym by it doesnt modify source files?

**Comment by ImAFrogOwO** [comment]
I modified BlurNSFW index.js

**Comment by rauenzi** [comment]
Since the function is the same for all, can you consolidate them? AKA one function that is the patch then 3 calls to patch the different context menus using the same function. Then the cancel functions can be pushed into an array rather than 3 separate and unclearly named cancel patched.

Also yes please remove both the `Added` section that you added to the README (as a changelog does not belong there) and the coming soon section can be removed because they would both be imeplemented/fixed here

**Comment by ImAFrogOwO** [comment]
Before I commit anything, I would do this all in the current /Plugins/BlurNSFW ? or src/plugins.

**Comment by rauenzi** [comment]
You should only be modifying the source of the plugin, you should undo all changes to the distribution version of the plugin. The README changes of course happen in that folder.

**Comment by rauenzi** [comment]
I guess I wasn't very detailed with what I meant before, but you have a lot of repeated code, so I think it would be better to do something like this:
```js
    constructor() {
        this.contextPatches = [];
    }
    
    onStart() {
        // Other stuff
        this.patchContextMenus();
    }
    
    patchContextMenus() {
        const patchFunction = (retVal, props) => {
            const newItem = ContextMenu.buildItem({
                type: "toggle",
                label: "Blur Media",
                active: this.hasBlur(props.channel),
                action: () => {
                    if (this.hasBlur(props.channel)) this.removeBlur(props.channel);
                    else this.addBlur(props.channel);
                }
            });

            retVal.props.children.splice(1, 0, newItem);
        });
        
        this.contextPatches.push(ContextMenu.patch("user-context", patchFunction));
        this.contextPatches.push(ContextMenu.patch("channel-context", patchFunction));
        this.contextPatches.push(ContextMenu.patch("gdm-context", patchFunction));
    }
```

Obviously with better formatting and such going on but I hope this gets across the idea of DRY I was shooting for.

**Comment by ImAFrogOwO** [comment]
Alright, I gotcha. 
Didn't even see the repeated code that wasn't being used, forgot to remove it. My apologizes.

**Comment by rauenzi** [comment]
Oh no worries, sorry about the confusion as well as the delay!

**Pull request merged**
