### PR TITLE
[BetterFormattingRedux] Latest version fix

### PR DESCRIPTION
**Pull request by Pleasant-exe**
Fix for BetterFormattingRedux as its not worked in a while, it would be nice to have the fix be on the official repo.

### CODE REVIEW

**Comment by SmolAlli** [comment]
https://github.com/rauenzi/BetterDiscordAddons/tree/master/src/plugins/BetterFormattingRedux
This will most likely not get merged, due to it not touching the source.

**Comment by BigBoss320** [comment]
how do we fix it ?

**Comment by Pleasant-exe** [comment]
> how do we fix it ?

https://github.com/rauenzi/BetterDiscordAddons/pull/618/commits/a68c8e8ca96a414738132562c3d382d7727ef1b7

**Comment by marcobiscoto** [comment]
doesn't work

**Comment by rauenzi** [comment]
Fixed at latest version, this does not touch the source files

**Pull request closed without merging**
