### PR TITLE
[BFRedux] Add cursor positioning feature for issue #721

### PR DESCRIPTION
**Pull request by KastanEr**
This pull request addresses issue #721 by introducing a new feature that improves the user experience when selecting a format type. With this enhancement, the cursor is now positioned between the left and right wrappers, facilitating easier typing for users.
Below is an example of execution.
스크린샷 2023-11-22 오후 2 35 09
스크린샷 2023-11-22 오후 2 31 36
스크린샷 2023-11-22 오후 2 31 47
And I applied code formatting for improved readability.

### CODE REVIEW

**Comment by rauenzi** [comment]
You only changed the compiled file and not the source file.

> And I applied code formatting for improved readability.

Please don't do this. It is good practice to follow the code style of the repository you are contributing to.

**Comment by rauenzi** [comment]
Not sure why this was closed, just address the issues mentioned previously

**Comment by KastanEr** [comment]
Sorry, this is my first time contributing, and I made a mistake. Can I just modify the relevant function in the source file, index.js, and send a pull request?

**Comment by rauenzi** [comment]
Yeah that would be great

**Pull request closed without merging**
