### PR TITLE
fixed HideDisabledEmoji

### PR DESCRIPTION
**Pull request by Tharki-God**
it was not working as you would have known so fixed it

### CODE REVIEW

**Comment by Tharki-God** [comment]
6yoym0

**Comment by M0REKZ** [comment]
aaaaaaaa

**Comment by schmurtzm** [comment]
PR working fine , @rauenzi  can you merge this ?

**Comment by zreong** [comment]
there seems to be some offset between the emoji I hover over and the emoji that the bar at the bottom displays
image

**Comment by SiJiL82** [comment]
It also splits the generic emoji category up so it appears in small sections under different servers, where their custom emoji normally are:
image

**Comment by M0REKZ** [comment]
also.... if you try to search an emoji, it will crash discord

**Comment by M0REKZ** [comment]
Rip

**Comment by Tharki-God** [comment]
> Rip

switched to replugged

**Comment by rauenzi** [comment]
This didn't even modify source file or have an explanation of changes

**Pull request closed without merging**
